---
name: Rubocop

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      TESTOPTS: "-v"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop --parallel